### ISSUE TITLE
Add filtering, sorting to all Data Table

### ISSUE THREAD

**Issue by aleku399** [motypes/eval-cso#221]
After adding the prop manual to the data table for the pagination to work a custom filtering and sorting is needed
[Sand box to show serverside filtering](https://codesandbox.io/s/217zyy837r?file=/index.js:2524-2532)
[React table v6](https://github.com/aakritsubedi/react-table-6.8.6#server-side-data)

**Comment by epicallan** [comment]
@aleku399 can we only enable client-side filtering and sorting for this demo and then we work on this task later on. I have ran out of time as of now.
