### ISSUE TITLE
Drop down for agents on Data Table  is omitted

### ISSUE THREAD

**Issue by aleku399** [motypes/eval-cso#223]
![Screenshot from 2021-03-22 17-59-30](https://user-images.githubusercontent.com/24989409/112011188-12d0c280-8b39-11eb-946a-75bef5698888.png)
Agent search options are commented  out for the code to work
![WhatsApp Image 2021-03-22 at 18 12 04](https://user-images.githubusercontent.com/24989409/112012427-3f390e80-8b3a-11eb-93a8-bc4287e441c3.jpeg)

**Comment by epicallan** [comment]
Agent search was actually within the agent name column
